In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
from statsmodels.formula.api import ols
import scipy.stats as stats
import math

pd.set_option('display.max_columns', 100, 'display.max_rows', 200)

from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("kc_house_data_train.csv")
address_df = pd.read_csv("full_seven7.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (16,21,24,27,28,29,30,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
address_df.rename(columns={'zipcode':'geom'}, inplace=True)

In [4]:
print(address_df.shape)
address_df.head()

(17290, 33)

,geom,house_number,road,neighbourhood,suburb,locality,county,state,postcode,country,country_code,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
0,"47.4388,-122.162",13408,Southeast 183rd Street,Forest Estates,Fairwood,Fairwood,King County,Washington,98058,United States of America,us,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"47.6784,-122.285",6825,40th Avenue Northeast,Laurelhurst,Wedgwood,NaN,King County,Washington,98115,United States of America,us,Seattle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"47.5646,-122.129",15899,Southeast 45th Street,NaN,Eastgate,NaN,King County,Washington,98006,United States of America,us,Bellevue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"47.6995,-122.228",10933,84th Place Northeast,NaN,NaN,NaN,King County,Washington,98034,United States of America,us,NaN,Finn Hill,Kirkland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"47.6647,-122.083",6534,192nd Place Northeast,NaN,NaN,NaN,King County,Washington,98052-6088,United States of America,us,NaN,Campton,Redmond,Woodbridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
address_df.isnull().sum()

geom                 0
house_number       996
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
state                0
postcode           102
country              0
country_code         0
city              6053
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [6]:
df["geom"] = df["lat"].map(str) + "," + df["long"].map(str)
df.head()

,Unnamed: 0,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,geom
0,0,2591820310,20141006T000000,365000.0,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,1986,0,98058,47.4388,-122.162,2390,7700,"47.4388,-122.162"
1,1,7974200820,20140821T000000,865000.0,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,1977,0,98115,47.6784,-122.285,2370,6283,"47.6784,-122.285"
2,2,7701450110,20140815T000000,1038000.0,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,1997,0,98006,47.5646,-122.129,3710,9685,"47.5646,-122.129"
3,3,9522300010,20150331T000000,1490000.0,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,1990,0,98034,47.6995,-122.228,4050,14226,"47.6995,-122.228"
4,4,9510861140,20140714T000000,711000.0,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2004,0,98052,47.6647,-122.083,2250,4050,"47.6647,-122.083"

In [7]:
df.shape

(17290, 23)

In [8]:
joined = df.merge(address_df.drop_duplicates(subset=['geom']),how='left')

In [9]:
joined.head()

,Unnamed: 0,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,geom,house_number,road,neighbourhood,suburb,locality,county,state,postcode,country,country_code,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
0,0,2591820310,20141006T000000,365000.0,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,1986,0,98058,47.4388,-122.162,2390,7700,"47.4388,-122.162",13408,Southeast 183rd Street,Forest Estates,Fairwood,Fairwood,King County,Washington,98058,United States of America,us,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,7974200820,20140821T000000,865000.0,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,1977,0,98115,47.6784,-122.285,2370,6283,"47.6784,-122.285",6825,40th Avenue Northeast,Laurelhurst,Wedgwood,NaN,King County,Washington,98115,United States of America,us,Seattle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,7701450110,20140815T000000,1038000.0,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,1997,0,98006,47.5646,-122.129,3710,9685,"47.5646,-122.129",15899,Southeast 45th Street,NaN,Eastgate,NaN,King County,Washington,98006,United States of America,us,Bellevue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,9522300010,20150331T000000,1490000.0,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,1990,0,98034,47.6995,-122.228,4050,14226,"47.6995,-122.228",10933,84th Place Northeast,NaN,NaN,NaN,King County,Washington,98034,United States of America,us,NaN,Finn Hill,Kirkland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,9510861140,20140714T000000,711000.0,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2004,0,98052,47.6647,-122.083,2250,4050,"47.6647,-122.083",6534,192nd Place Northeast,NaN,NaN,NaN,King County,Washington,98052-6088,United States of America,us,NaN,Campton,Redmond,Woodbridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
joined.drop(['Unnamed: 0','state','house_number','postcode','country','country_code'], axis=1, inplace=True)

In [11]:
joined.isnull().shape

(17290, 49)

In [12]:
joined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17290 entries, 0 to 17289
Data columns (total 49 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             17290 non-null  int64
 1   date           17290 non-null  object
 2   price          17290 non-null  float64
 3   bedrooms       17290 non-null  int64
 4   bathrooms      17290 non-null  float64
 5   sqft_living    17290 non-null  int64
 6   sqft_lot       17290 non-null  int64
 7   floors         17290 non-null  float64
 8   waterfront     17290 non-null  int64
 9   view           17290 non-null  int64
 10  condition      17290 non-null  int64
 11  grade          17290 non-null  int64
 12  sqft_above     17290 non-null  int64
 13  sqft_basement  17290 non-null  int64
 14  yr_built       17290 non-null  int64
 15  yr_renovated   17290 non-null  int64
 16  zipcode        17290 non-null  int64
 17  lat            17290 non-null  float64
 18  long           17290 non-null  float64
 19  sqft_living15  17290 non-null  int64
 20  sqft_lot15     17290 non-null  int64
 21  geom           17290 non-null  object
 22  road           17107 non-null  object
 23  neighbourhood  8132 non-null   object
 24  suburb         5315 non-null   object
 25  locality       1207 non-null   object
 26  county         17290 non-null  object
 27  city           11237 non-null  object
 28  hamlet         9486 non-null   object
 29  town           4187 non-null   object
 30  residential    1061 non-null   object
 31  amenity        169 non-null    object
 32  farmyard       1 non-null      object
 33  natural        65 non-null     object
 34  building       57 non-null     object
 35  leisure        66 non-null     object
 36  village        73 non-null     object
 37  place          8 non-null      object
 38  shop           17 non-null     object
 39  retail         16 non-null     object
 40  highway        4 non-null      object
 41  office         7 non-null      object
 42  commercial     10 non-null     object
 43  historic       4 non-null      object
 44  craft          3 non-null      object
 45  industrial     3 non-null      object
 46  tourism        3 non-null      object
 47  man_made       2 non-null      object
 48  railway        1 non-null      object
dtypes: float64(5), int64(15), object(29)
memory usage: 6.6+ MB

In [13]:
# joined[joined['postcode']=='98052-6088']

# joined['post'] = np.where(joined['postcode']=='98052-6088', joined['zipcode'], joined['postcode'])

# joined['post2'] = np.where(joined['postcode']=="98106-1499", joined['zipcode'], joined['post'])


# joined['post3'] = np.where(joined['postcode']=="98133-6124", joined['zipcode'], joined['post2'])

# joined['post3'] = np.where(joined['postcode']=="98133-6124", joined['zipcode'], joined['post2'])

# joined['post3'] = np.where(joined['postcode']=="98133-6124", joined['zipcode'], joined['post2'])

# joined['post3'] = np.where(joined['postcode']=="98133-6124", joined['zipcode'], joined['post2'])

# joined.head()

In [14]:
joined.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
0,2591820310,20141006T000000,365000.0,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,1986,0,98058,47.4388,-122.162,2390,7700,"47.4388,-122.162",Southeast 183rd Street,Forest Estates,Fairwood,Fairwood,King County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7974200820,20140821T000000,865000.0,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,1977,0,98115,47.6784,-122.285,2370,6283,"47.6784,-122.285",40th Avenue Northeast,Laurelhurst,Wedgwood,NaN,King County,Seattle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7701450110,20140815T000000,1038000.0,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,1997,0,98006,47.5646,-122.129,3710,9685,"47.5646,-122.129",Southeast 45th Street,NaN,Eastgate,NaN,King County,Bellevue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9522300010,20150331T000000,1490000.0,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,1990,0,98034,47.6995,-122.228,4050,14226,"47.6995,-122.228",84th Place Northeast,NaN,NaN,NaN,King County,NaN,Finn Hill,Kirkland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9510861140,20140714T000000,711000.0,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2004,0,98052,47.6647,-122.083,2250,4050,"47.6647,-122.083",192nd Place Northeast,NaN,NaN,NaN,King County,NaN,Campton,Redmond,Woodbridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city              6053
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [17]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98001,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,173,47,139,161,173,0,20,12,11,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98002,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98003,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,220,85,34,34,220,0,3,175,1,0,0,1,0,0,11,0,0,2,0,0,0,0,0,0,0,0,0
98004,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,61,0,0,0,64,0,5,24,0,1,0,2,0,1,40,0,0,0,0,0,0,0,0,0,0,0,0
98007,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98008,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,4,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98010,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,4,0,0,27,0,27,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98011,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,4,0,0,6,0,6,6,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98014,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,78,0,0,27,80,0,66,5,0,1,0,7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
98019,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,0,0,1,28,0,13,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98022,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,22,0,1,189,0,175,134,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98023,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,198,0,0,409,0,100,409,17,2,0,3,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
98024,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,60,4,0,24,65,0,58,12,0,2,0,1,1,0,21,0,0,0,0,0,0,0,0,0,0,0,0
98027,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,325,100,6,60,330,0,271,241,97,5,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
98029,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,112,10,0,0,131,0,126,130,113,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
98031,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98032,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1,2,4,0,3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98033,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,351,43,107,0,355,0,248,354,11,3,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98034,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,428,195,51,0,430,0,379,430,4,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98038,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,453,379,2,4,453,0,451,413,12,2,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98039,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98042,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,47,0,83,92,0,76,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98045,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,171,49,0,0,176,0,176,49,2,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98052,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,474,461,159,0,48,474,0,473,424,168,7,0,1,1,1,0,0,2,0,0,0,1,0,0,0,0,0,0
98053,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,0,172,28,320,0,114,290,141,1,0,2,7,0,0,0,0,0,0,0,2,0,0,0,0,0,0
98056,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,5,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98058,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,263,164,112,251,263,0,34,0,4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,13,54,0,117,0,62,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,219,172,0,0,249,0,230,231,16,3,0,1,0,11,0,0,0,0,0,1,0,2,0,0,1,0,0
98070,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,88,14,0,0,99,0,99,99,5,1,0,0,1,5,0,0,0,0,0,0,0,1,0,0,1,0,0
98072,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,94,0,0,94,96,0,96,2,6,1,0,0,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0
98074,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98077,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,161,0,1,144,162,0,160,18,62,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98092,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,19,5,10,71,0,66,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98106,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98146,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,106,89,0,175,0,52,108,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98148,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,39,25,0,0,40,0,34,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98166,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,82,0,0,141,0,39,141,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98168,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,51,27,0,155,0,91,126,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
98178,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,130,64,0,130,130,0,108,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98188,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,86,0,0,0,87,0,87,87,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98198,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,199,0,0,216,0,51,216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [18]:
joined.loc[joined['city'].isnull(),'city'] = joined['locality']

In [19]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98001,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0,12,0,12,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98002,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98003,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,186,76,26,0,186,0,3,175,1,0,0,0,0,0,11,0,0,2,0,0,0,0,0,0,0,0,0
98004,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,61,0,0,0,64,0,5,24,0,1,0,2,0,1,40,0,0,0,0,0,0,0,0,0,0,0,0
98007,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98008,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,4,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98010,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,4,0,0,27,0,27,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98011,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,4,0,0,6,0,6,6,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98014,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,51,0,0,0,53,0,39,5,0,1,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
98019,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,0,0,0,27,0,12,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98022,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,188,22,0,0,188,0,174,134,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98023,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,198,0,0,409,0,100,409,17,2,0,3,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
98024,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,36,4,0,0,41,0,36,12,0,1,0,1,1,0,21,0,0,0,0,0,0,0,0,0,0,0,0
98027,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,265,57,6,0,270,0,211,241,97,5,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
98029,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,131,112,10,0,0,131,0,126,130,113,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
98032,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,2,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98033,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,355,351,43,107,0,355,0,248,354,11,3,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98034,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,430,428,195,51,0,430,0,379,430,4,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98038,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,449,376,2,0,449,0,447,413,12,2,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98039,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98042,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,7,0,0,9,0,9,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98045,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,176,171,49,0,0,176,0,176,49,2,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98052,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,426,414,159,0,0,426,0,425,424,167,6,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0
98053,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,292,0,172,0,292,0,86,290,141,1,0,0,7,0,0,0,0,0,0,0,2,0,0,0,0,0,0
98056,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,5,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98058,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,4,4,0,12,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,13,54,0,117,0,62,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,219,172,0,0,249,0,230,231,16,3,0,1,0,11,0,0,0,0,0,1,0,2,0,0,1,0,0
98070,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,88,14,0,0,99,0,99,99,5,1,0,0,1,5,0,0,0,0,0,0,0,1,0,0,1,0,0
98072,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98074,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98077,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,17,0,1,0,18,0,16,18,15,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98092,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,14,5,0,61,0,56,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98106,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98146,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175,106,89,0,175,0,52,108,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98148,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,39,25,0,0,40,0,34,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98166,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141,82,0,0,141,0,39,141,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98168,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,51,27,0,155,0,91,126,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
98188,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,86,0,0,0,87,0,87,87,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98198,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216,199,0,0,216,0,51,216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [20]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city              4950
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [21]:
joined.loc[joined['city'].isnull(),'city'] = joined['town']

In [22]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98002,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98003,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0,0,0,11,0,3,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0
98004,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,38,0,0,0,40,0,0,0,0,1,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0
98010,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,4,0,0,26,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98014,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,46,0,0,0,48,0,39,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
98019,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,0,0,0,27,0,12,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98022,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,6,0,0,54,0,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98024,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,24,4,0,0,29,0,25,0,0,1,0,1,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0
98027,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,8,6,0,29,0,24,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98029,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98032,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,2,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98033,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98038,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,16,2,0,36,0,34,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98042,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,7,0,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98045,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,123,41,0,0,127,0,127,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98052,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98053,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98056,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,5,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98058,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,4,4,0,12,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,13,54,0,117,0,62,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,5,0,0,18,0,17,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98074,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98092,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,14,5,0,61,0,56,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98106,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98146,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,15,67,0,67,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98168,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,4,18,0,29,0,11,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [23]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city               763
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [24]:
joined.loc[joined['city'].isnull(),'city'] = joined['suburb']

In [25]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98002,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98003,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0,0,0,11,0,3,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0
98004,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,38,0,0,0,40,0,0,0,0,1,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0
98010,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,4,0,0,26,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98014,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,46,0,0,0,48,0,39,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
98019,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,0,0,0,27,0,12,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98022,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,6,0,0,54,0,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98024,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,24,4,0,0,29,0,25,0,0,1,0,1,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0
98027,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,8,0,0,23,0,19,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98029,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98032,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,2,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98033,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98038,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,16,0,0,34,0,34,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98042,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,7,0,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98045,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,123,41,0,0,127,0,127,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98052,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98053,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98056,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,5,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98058,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,4,0,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,13,0,0,63,0,50,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,5,0,0,18,0,17,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98074,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98092,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,14,0,0,56,0,56,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98168,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,1,0,0,11,0,11,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [26]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city               599
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [27]:
joined.loc[joined['city'].isnull(),'city'] = joined['neighbourhood']

In [28]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98003,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0,0,0,11,0,3,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0
98004,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,38,0,0,0,40,0,0,0,0,1,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0
98010,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,0,0,0,22,0,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98014,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,46,0,0,0,48,0,39,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
98019,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,0,0,0,27,0,12,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98022,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,0,0,0,48,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98024,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,20,0,0,0,25,0,21,0,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0,0,0,0
98027,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0,0,0,15,0,13,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98033,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98038,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,0,0,0,18,0,18,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98042,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98045,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,82,0,0,0,86,0,86,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98052,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98053,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98058,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,0,0,0,50,0,47,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,0,0,0,13,0,12,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98074,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98092,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,0,0,0,42,0,42,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
98168,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,0,0,0,10,0,10,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city               467
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [30]:
joined.loc[joined['city'].isnull(),'city'] = joined['hamlet']

In [31]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98003,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0,0,0,8,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0
98004,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,38,0,0,0,40,0,0,0,0,1,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0
98014,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98019,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0,0,0,15,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98024,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,0,0,0,4,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0
98027,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [32]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city                82
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [33]:
joined.loc[joined['city'].isnull(),'city'] = joined['village']

In [34]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98014,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98019,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0,0,0,15,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98027,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [35]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city                30
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [36]:
joined.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
geom              object
road              object
neighbourhood     object
suburb            object
locality          object
county            object
city              object
hamlet            object
town              object
residential       object
amenity           object
farmyard          object
natural           object
building          object
leisure           object
village           object
place             object
shop              object
retail            object
highway           object
office            object
commercial        object
historic          object
craft             object
industrial        object
tourism           object
man_made          object
railway           object
dtype: object

In [37]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98014,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98019,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0,0,0,15,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98027,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [38]:
# joined['city'] = np.where((joined['city'].isnull() & joined['zipcode']==98014), 'Carnation', joined['city'])

In [39]:
# joined[joined['city'].isnull()].groupby('zipcode').count()

In [40]:
# joined = joined.assign(
#     city2=np.where(joined['city'].isnull() & joined['zipcode']==98019, 'Duvall', joined['city'])
# )

In [41]:
joined.loc[(joined['city'].isnull()) & (joined['zipcode']==98014), 'city'] = 'Carnation'

In [42]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98019,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0,0,0,15,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98027,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [43]:
joined.loc[(joined['city'].isnull()) & (joined['zipcode']==98019), 'city'] = 'Duvall'

In [44]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98027,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [45]:
joined.loc[(joined['city'].isnull()) & (joined['zipcode']==98027), 'city'] = 'Issaquah'

In [46]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [47]:
joined.loc[(joined['city'].isnull()) & (joined['zipcode']==98059), 'city'] = 'Renton'

In [48]:
joined[joined['city'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [49]:
joined.loc[(joined['city'].isnull()) & (joined['zipcode']==98065), 'city'] = 'Snoqualmie'

In [50]:
joined[joined['city'].isnull()].groupby('zipcode').count()

Empty DataFrame
Columns: [id, date, price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, lat, long, sqft_living15, sqft_lot15, geom, road, neighbourhood, suburb, locality, county, city, hamlet, town, residential, amenity, farmyard, natural, building, leisure, village, place, shop, retail, highway, office, commercial, historic, craft, industrial, tourism, man_made, railway]
Index: []

In [53]:
joined.isnull().sum()

id                   0
date                 0
price                0
bedrooms             0
bathrooms            0
sqft_living          0
sqft_lot             0
floors               0
waterfront           0
view                 0
condition            0
grade                0
sqft_above           0
sqft_basement        0
yr_built             0
yr_renovated         0
zipcode              0
lat                  0
long                 0
sqft_living15        0
sqft_lot15           0
geom                 0
road               183
neighbourhood     9158
suburb           11975
locality         16083
county               0
city                 0
hamlet            7804
town             13103
residential      16229
amenity          17121
farmyard         17289
natural          17225
building         17233
leisure          17224
village          17217
place            17282
shop             17273
retail           17274
highway          17286
office           17283
commercial       17280
historic         17286
craft            17287
industrial       17287
tourism          17287
man_made         17288
railway          17289
dtype: int64

In [62]:
null_cols = joined[joined.columns[joined.isnull().all()]]
# joined.drop(null_cols, axis = 1, inplace = True)

In [63]:
null_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[17290 rows x 0 columns]

In [60]:
smaller_df = joined[joined.columns[~joined.isnull().any()]]
smaller_df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,geom,county,city
0,2591820310,20141006T000000,365000.0,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,1986,0,98058,47.4388,-122.162,2390,7700,"47.4388,-122.162",King County,Fairwood
1,7974200820,20140821T000000,865000.0,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,1977,0,98115,47.6784,-122.285,2370,6283,"47.6784,-122.285",King County,Seattle
2,7701450110,20140815T000000,1038000.0,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,1997,0,98006,47.5646,-122.129,3710,9685,"47.5646,-122.129",King County,Bellevue
3,9522300010,20150331T000000,1490000.0,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,1990,0,98034,47.6995,-122.228,4050,14226,"47.6995,-122.228",King County,Kirkland
4,9510861140,20140714T000000,711000.0,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2004,0,98052,47.6647,-122.083,2250,4050,"47.6647,-122.083",King County,Redmond

In [61]:
smaller_df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
geom             0
county           0
city             0
dtype: int64

In [64]:
smaller_df.to_csv('with_cities.csv')

In [95]:
smaller_df.groupby('city')['price'].median().sort_values(ascending=False)

city
Medina                        1880000.0
Clyde Hill                    1662500.0
Yarrow Point                  1629000.0
Hunts Point                   1600000.0
Avondale                      1325000.0
High Point                    1317500.0
Beaux Arts Village            1291500.0
Mercer Island                  989900.0
Tibbetts Station               925000.0
River Si Estates               845000.0
Inglewood                      799990.0
Franklin                       780000.0
Cougar Hills                   743500.0
Earlmont                       725000.0
Coal Creek                     725000.0
South Firs                     725000.0
Sunridge at Elk Run            720000.0
Bellevue                       719000.0
Union Hill-Novelty Hill        680000.0
Landsburg                      675000.0
Sammamish                      664000.0
Chateaus at the Greenbrier     650000.0
Novelty                        640000.0
Redmond                        624000.0
Sycamore                       620000.0
Newcastle                      605000.0
Cottage Lake                   602500.0
Coalfield                      600000.0
White                          597500.0
Ames Lake                      590000.0
Riverpoint                     590000.0
The Grove at Spring Lake       589950.0
Ravensdale                     589450.0
Issaquah                       585000.0
High Valley                    575000.0
Wilderness Village             565000.0
Wildernness Downs              555000.0
Mirrormont                     542500.0
Pleasant Hill                  533750.0
Ravenswood                     525888.0
Snoqualmie Pass                525000.0
Normandy Park                  516000.0
Snoqualmie                     515000.0
Hobart                         513000.0
Preston                        510000.0
Seattle                        510000.0
Kirkland                       509000.0
Stillwater                     507500.0
Woodinville                    496500.0
Spring Glen                    486000.0
Edgewick                       480000.0
Tanner                         476995.0
Krain                          475000.0
Snoqualmie Falls               474950.0
Kerriston                      472000.0
Ellisville                     471000.0
Bothell                        470000.0
Timberlane                     470000.0
Vashon                         467500.0
Lake Forest Park               464750.0
Kenmore                        448500.0
Maple Heights-Lake Desire      448000.0
Wabash                         437000.0
North Bend                     432900.0
Trude                          424900.0
Fall City                      422500.0
Kummer                         418200.0
Four Creeks                    415000.0
Durham                         415000.0
Cedar Grove                    414250.0
Wynaco                         413000.0
Palmer                         408506.0
Harman Heights                 403475.0
Duvall                         402750.0
Wyngates                       400000.0
Muckleshoot                    399000.0
Newaukum                       397500.0
Kanaskat Junction              390000.0
Upper Preston                  387000.0
East Renton Highlands          380250.0
Greenwater                     380000.0
Palisades                      378000.0
Lake Marcel-Stillwater         375000.0
Crofton Hills                  375000.0
Shoreline                      375000.0
Cambridge East                 374000.0
Veazie                         370000.0
Maple Woods                    369000.0
Maple Hills                    356000.0
The Ridge at Lake Sawyer       353000.0
Ernies Grove                   352500.0
Maplewood Heights              350000.0
Crestview                      350000.0
Glacier Vista                  350000.0
Fairwood                       346500.0
Willowbrook                    345500.0
Upper Mill                     340000.0
Mountlake Terrace              339000.0
Riverbend                      335000.0
Renton                         335000.0
Osceola                        327000.0
Kanaskat                       325000.0
Maple Valley                   324925.0
One Hundred One Pines          320000.0
Grotto                         320000.0
Carnation                      311000.0
Lake Morton-Berrydale          311000.0
Hidden Creek                   310650.0
East Hill-Meridian             308500.0
Milton                         305850.0
Black Diamond                  304624.5
Wilderness Rim                 295000.0
Kent                           290000.0
Maplewood                      285847.5
Bryn Mawr-Skyway               285000.0
Eagle Nest                     281250.0
Burien                         278750.0
Auburn                         273000.0
Glendale                       272500.0
Fife Heights                   272000.0
Des Moines                     272000.0
Southern Heights               270000.0
Glencoe                        269950.0
Covington                      269950.0
Cumberland                     269000.0
Lakeland North                 266250.0
Federal Way                    266000.0
South Park                     265000.0
Lakeland South                 263400.0
Enumclaw                       262250.0
White Center                   255000.0
Tukwila                        251500.0
Meadowbrook                    250000.0
SeaTac                         245000.0
King County                    230350.0
Pacific                        230000.0
Mystic Acres                   220000.0
Maple Valley Heights           210000.0
Algona                         198975.0
Tacoma                         179950.0
Baring                         170000.0
Skykomish                      155000.0
Name: price, dtype: float64

In [94]:
smaller_df.groupby('city')['city'].count().sort_values(ascending=False)

city
Seattle                       5400
Bellevue                      1040
Renton                         794
Kirkland                       788
Sammamish                      763
Kent                           661
Federal Way                    594
Shoreline                      519
Redmond                        431
Auburn                         429
Burien                         380
Maple Valley                   360
Issaquah                       359
Union Hill-Novelty Hill        314
Cottage Lake                   286
Snoqualmie                     235
Mercer Island                  229
Kenmore                        217
Des Moines                     217
Covington                      203
Fairwood                       189
Bothell                        167
Lake Forest Park               134
Enumclaw                       134
Duvall                         132
Bryn Mawr-Skyway               130
SeaTac                         123
Woodinville                    117
Newcastle                      115
Lakeland North                 110
Vashon                          99
Tukwila                         94
White Center                    93
Lakeland South                  87
Lake Morton-Berrydale           76
Normandy Park                   74
Mirrormont                      68
East Renton Highlands           66
Hobart                          55
Ames Lake                       51
North Bend                      49
Black Diamond                   48
East Hill-Meridian              42
Medina                          42
Clyde Hill                      40
Maple Heights-Lake Desire       38
Wilderness Rim                  37
Pacific                         32
Carnation                       30
Wynaco                          29
Fall City                       28
Tanner                          28
Maplewood Heights               27
Riverbend                       26
Stillwater                      26
Ravensdale                      23
Preston                         23
Lake Marcel-Stillwater          23
Algona                          20
Yarrow Point                    17
Newaukum                        14
Maple Woods                     14
Edgewick                        13
Kummer                          13
Krain                           11
Maple Hills                     10
Pleasant Hill                   10
Willowbrook                     10
Harman Heights                  10
The Ridge at Lake Sawyer         9
Veazie                           9
Milton                           8
Glendale                         8
One Hundred One Pines            8
Wabash                           8
Spring Glen                      7
Wilderness Village               7
Upper Preston                    7
Ellisville                       6
High Point                       6
Muckleshoot                      5
Ernies Grove                     5
Coalfield                        5
Glacier Vista                    5
Glencoe                          5
The Grove at Spring Lake         5
High Valley                      5
Upper Mill                       5
Snoqualmie Falls                 5
Skykomish                        5
Cumberland                       4
Eagle Nest                       4
Timberlane                       4
Beaux Arts Village               4
Coal Creek                       4
Four Creeks                      4
Riverpoint                       3
Crestview                        3
Novelty                          3
Osceola                          3
Fife Heights                     3
Hunts Point                      3
Hidden Creek                     3
Maplewood                        2
Cougar Hills                     2
Kerriston                        2
Southern Heights                 2
Cedar Grove                      2
Kanaskat Junction                2
King County                      2
Wildernness Downs                1
Tibbetts Station                 1
White                            1
Avondale                         1
Baring                           1
Chateaus at the Greenbrier       1
Trude                            1
Crofton Hills                    1
Cambridge East                   1
Mountlake Terrace                1
Durham                           1
Earlmont                         1
Mystic Acres                     1
Meadowbrook                      1
Maple Valley Heights             1
Wyngates                         1
Landsburg                        1
Palisades                        1
Palmer                           1
Ravenswood                       1
River Si Estates                 1
Kanaskat                         1
Snoqualmie Pass                  1
Inglewood                        1
South Firs                       1
Grotto                           1
Greenwater                       1
South Park                       1
Sunridge at Elk Run              1
Sycamore                         1
Tacoma                           1
Franklin                         1
Name: city, dtype: int64

In [41]:
# joined[joined['city2'].isnull()].groupby('zipcode').count()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,geom,road,neighbourhood,suburb,locality,county,city,hamlet,town,residential,amenity,farmyard,natural,building,leisure,village,place,shop,retail,highway,office,commercial,historic,craft,industrial,tourism,man_made,railway,city2
zipcode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
98014,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98019,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,0,0,0,15,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98027,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98059,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
98065,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [60]:
# joined['city'] = np.where(joined['city'].isnull() & joined['zipcode']==98014, 'Carnation', joined['city'])

In [50]:
# joined['city'] = np.where(joined['city'].isnull() & joined['zipcode']==98019, 'Duvall', joined['city'])

In [59]:
# joined[joined['city'].isnull()]

In [27]:
joined[['neighbourhood','suburb','locality','city','hamlet','town','residential','amenity']]

,neighbourhood,suburb,locality,city,hamlet,town,residential,amenity
0,Forest Estates,Fairwood,Fairwood,Fairwood,NaN,NaN,NaN,NaN
1,Laurelhurst,Wedgwood,NaN,Seattle,NaN,NaN,NaN,NaN
2,NaN,Eastgate,NaN,Bellevue,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Kirkland,Finn Hill,Kirkland,NaN,NaN
4,NaN,NaN,NaN,Redmond,Campton,Redmond,Woodbridge,NaN
...,...,...,...,...,...,...,...,...
17285,Sammamish Heights,NaN,NaN,Bellevue,Vasa Park,NaN,NaN,NaN
17286,NaN,NaN,NaN,Seattle,Inverness,NaN,NaN,NaN
17287,NaN,NaN,NaN,Kenmore,Moorlands,NaN,NaN,NaN
17288,NaN,NaN,NaN,Hobart,Atkinson,Hobart,NaN,NaN
17289,North City,NaN,NaN,Shoreline,Paramount Park,NaN,NaN,NaN

In [28]:
# joined["zipcode"] = joined["zipcode"].str.strip()
# joined["postcode"] = joined["postcode"].str.strip()

In [29]:
# joined['low_value'] = np.where(joined['zipcode'] == joined['postcode'], 'True', 'False')

In [30]:
# joined.low_value.value_counts()

In [31]:
# joined[['zipcode','postcode']]

In [ ]:
from shapely.geometry import Point, Polygon
import geopandas as gpd
from geopandas import GeoDataFrame
import descartes
import libpysal 
import mapclassify

fig, ax = plt.subplots(1, figsize=(40, 20))
ax.axis('auto')
ax.set_title('Heat Map of Avg Price by Zipcodes in King County, Washington', fontdict={'fontsize': '40', 'fontweight' : '3'})

# geomet = [Point(xy) for xy in zip(city_df['long'], city_df['lat'])]
# gdf = GeoDataFrame(city_df, geometry=geomet,crs="EPSG:4326")  
# gdf.plot(ax=ax, markersize=20, color='blue', marker = 'o', label = "Long,Lat")
# # regions.plot(cmap=color,ax=ax, alpha = 0.4)

color = 'Reds'
vmin, vmax = 0, 231
sm = plt.cm.ScalarMappable(cmap=color, norm=plt.Normalize(vmin=vmin, vmax=vmax))
sm._A = []
cbar = fig.colorbar(sm)
cbar.ax.tick_params(labelsize=20)

# regions.plot()
plot_df.plot('price', cmap=color, scheme='Quantiles', k=10,linewidth=0.3, ax=ax, edgecolor='white', figsize=(40,20))
plt.show()